### ISSUE TITLE
Modifier and shortcut help

### ISSUE THREAD

**Issue by SomeUserName1** [cosminadrianpopescu/azul#3] opened 2024-12-16 11:39 UTC
Hi,

first of all: thanks. Awesome piece of software. 
I've been looking for something like this for a while. It's a shame that it hasn't gone viral yet, but I think it definitely has the potential.

Quoting from the docs:
> Unlike tmux workflow, when you click the modifier azul will remain in TERMINAL mode, but will wait for the next key and is going to interpret it like an azul command. If you wait for 300 ms, then you will also have a help indicating what are the possible commands that you can send to azul.

If i hit the modifier <C-s>, the next key is only enterable for 300ms.
After that, the terminal will inperpret <C-s> - forward search in the case of zsh - and the next key will just go to the terminal.
Thus, no help pops up. 

I think the help on no-enter second key is an essential feature to get started more quickly and flatten the learning curve (just like the help that pops up in LazyVim if you use the leader/space bar).

Did I forget to set something up properly, is this an issue with keymap collision on Zsh or is this maybe a bug?

So overall I'm not sure if I'm reading the docs incorrectly, if this is a bug report or rather a feature request.

Please advise & thanks in advance 
Fabian

**Comment by cosminadrianpopescu** [comment] 2024-12-16 14:17
The help is only available in `azul` workflow mode. Do you use the `tmux` workflow by any chance?

**Comment by cosminadrianpopescu** [comment] 2024-12-16 14:38
Never mind. I could reproduce the bug locally. I will have a fix shortly.

**Comment by cosminadrianpopescu** [comment] 2024-12-16 14:53
This is because of a change in the which-key plugin which I need to investigate. As a temporary workaround, you can do this:

```bash
cd ~/.config/azul/pack/start/which-key/
git checkout 6c1584eb76b55629702716995cca4ae2798a9cca
```
And then restart azul. This will revert the which-key plugin to the 3.13.2 version, that should be ok. 

I probably won't fix this, since I plan anyway to drop this plugin and to implement in azul the help window, without the need of the `which-key` plugin. So, use the workaround for the moment and then when I will have a new version that does not require this plugin, it should be ok. 

Let me know if this fixes the issue for the moment.

**Comment by SomeUserName1** [comment] 2024-12-16 15:11
Nit: `cd ~/.config/azul/pack/start/which-key.nvim/ `

Errors with:
```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
E5108: Error executing lua: /home/fklopfer/.local/share/azul/nvim/lua/azul.lua:789: non-float cannot have 'col'                                                                                                                                                                                                                                                                                                                                                                                
stack traceback:                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
        [C]: in function 'nvim_win_set_config'                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        /home/fklopfer/.local/share/azul/nvim/lua/azul.lua:789: in function 'position_current_float'                                                                                                                                                                                                                                                                                                                                                                                           
        /home/fklopfer/.config/azul/init.lua:161: in function </home/fklopfer/.config/azul/init.lua:160> 
```

Stuck in move mode persists. 
However I don't use that atm, so feel free to take your time. :slightly_smiling_face:

**Comment by cosminadrianpopescu** [comment] 2024-12-16 15:21
What version of neovim you use?

**Comment by SomeUserName1** [comment] 2024-12-16 15:23
v0.10.2

I've just purged everything (the azul folders in .config/** and .local**) and reinstalled. Now i get 
```
 azul -a travis
azul: line 127: --server: command not found
```
Which is kind of confuding as 
```
nvim --server
nvim: Argument missing after: "--server"
More info with "nvim -h"
```

**Closed** 2024-12-16 15:29 UTC

**Comment by SomeUserName1** [comment] 2024-12-16 15:46
That was just my stupidity. I executed azul from the git repo so it took that script instead of .local/bin from $PATH

**Comment by cosminadrianpopescu** [comment] 2024-12-16 16:18
I've pushed a new commit which should fix all the plugins that azul is using to certain versions. This should prevent further issues on re-install. Try to update and re-install everything from scratch, if possible.

**Comment by SomeUserName1** [comment] 2024-12-16 17:10
The last commit is from 2 hours ago and that i already installed after purging.

For that the versions aren't fixed but all are on master besides which-keys, that i've set to the commit you mentioned by hand.
